### ISSUE TITLE
need parameters in conf file...

### ISSUE THREAD

**Issue by hpacaman** [litecoinz-core/litecoinz#26]
need this parameters in conf file after v3.0.0 and v3.0.1:

addresstype=legacy
changetype=legacy
fallbackfee=0.0002

**Comment by MarkLTZ** [comment]
Dear @hpacaman thank you very much for your feedback.

We discovered some issues on latest release. The ones mentioned by you are fixed by:
- https://github.com/litecoinz-core/litecoinz/commit/83ae17584a0060cf9347346cd1c506de3514d557 (fallbackfee)
- https://github.com/litecoinz-core/litecoinz/commit/c9895639be4fec9843c4a93f1b93a4946a7a9113 (addresstype/changetype)

I've also modified the Known issues section https://github.com/litecoinz-core/litecoinz/releases/tag/v3.0.1

Best regards,
Mark

**Comment by MarkLTZ** [comment]
Please, add also paytxfee=0.0001 in your litecoinz.conf
